package com.codingpit.muviss.feature.settings.domain

/** One dependency's license grant, as shown on the Settings > About > Licenses screen. */
data class OssLicense(
    val groupId: String,
    val artifactId: String,
    val name: String,
    val licenseName: String,
    val licenseUrl: String?,
)

/**
 * Every direct + transitive OSS dependency this app ships, with its
 * license — generated from `app.cash.licensee`'s report
 * (`:app:androidApp:licenseeAndroidRelease`, see `app/androidApp/build.gradle.kts`
 * and docs/RELEASING.md "OSS licenses"). Regenerate by re-running that task
 * against `app/androidApp/build/reports/licensee/androidRelease/artifacts.json`
 * and refreshing this list — there is no live Gradle wiring from that report
 * into this KMP module (the report only covers the Android dependency graph;
 * Android is this app's primary target, see CLAUDE.md).
 */
val ossLicenses: List<OssLicense> = listOf(
    OssLicense("androidx.activity", "activity", "Activity", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.activity", "activity-compose", "Activity Compose", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.activity", "activity-ktx", "Activity Kotlin Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.annotation", "annotation", "Annotation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.annotation", "annotation-experimental", "Experimental annotation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.annotation", "annotation-jvm", "Annotation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.appcompat", "appcompat", "AppCompat", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.appcompat", "appcompat-resources", "AppCompat Resources", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.arch.core", "core-common", "Android Arch-Common", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.arch.core", "core-runtime", "Android Arch-Runtime", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.autofill", "autofill", "AndroidX Autofill", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.collection", "collection", "collections", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.collection", "collection-jvm", "collections", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.collection", "collection-ktx", "Collections Kotlin Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.animation", "animation", "Compose Animation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.animation", "animation-android", "Compose Animation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.animation", "animation-core", "Compose Animation Core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.animation", "animation-core-android", "Compose Animation Core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.foundation", "foundation", "Compose Foundation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.foundation", "foundation-android", "Compose Foundation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.foundation", "foundation-layout", "Compose Layouts", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.foundation", "foundation-layout-android", "Compose Layouts", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.material", "material-ripple", "Compose Material Ripple", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.material", "material-ripple-android", "Compose Material Ripple", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.material3", "material3", "Compose Material3 Components", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.material3", "material3-adaptive-navigation-suite", "Material Adaptive Navigation Suite", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.material3", "material3-adaptive-navigation-suite-android", "Material Adaptive Navigation Suite", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.material3", "material3-android", "Compose Material3 Components", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.material3.adaptive", "adaptive", "Material Adaptive", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.material3.adaptive", "adaptive-android", "Material Adaptive", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.runtime", "runtime", "Compose Runtime", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.runtime", "runtime-android", "Compose Runtime", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.runtime", "runtime-annotation", "Compose Runtime Annotation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.runtime", "runtime-annotation-android", "Compose Runtime Annotation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.runtime", "runtime-retain", "Compose Runtime Retain", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.runtime", "runtime-retain-android", "Compose Runtime Retain", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.runtime", "runtime-saveable", "Compose Saveable", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.runtime", "runtime-saveable-android", "Compose Saveable", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.ui", "ui", "Compose UI", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.ui", "ui-android", "Compose UI", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.ui", "ui-geometry", "Compose Geometry", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.ui", "ui-geometry-android", "Compose Geometry", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.ui", "ui-graphics", "Compose Graphics", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.ui", "ui-graphics-android", "Compose Graphics", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.ui", "ui-text", "Compose UI Text", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.ui", "ui-text-android", "Compose UI Text", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.ui", "ui-tooling-preview", "Compose UI Preview Tooling", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.ui", "ui-tooling-preview-android", "Compose UI Preview Tooling", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.ui", "ui-unit", "Compose Unit", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.ui", "ui-unit-android", "Compose Unit", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.ui", "ui-util", "Compose Util", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.compose.ui", "ui-util-android", "Compose Util", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.concurrent", "concurrent-futures", "AndroidX Futures", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.concurrent", "concurrent-futures-ktx", "AndroidX Futures Kotlin Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.core", "core", "Core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.core", "core-ktx", "Core Kotlin Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.core", "core-remoteviews", "RemoteViews", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.core", "core-viewtree", "androidx.core:core-viewtree", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.cursoradapter", "cursoradapter", "Android Support Library Cursor Adapter", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.customview", "customview", "Android Support Library Custom View", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.customview", "customview-poolingcontainer", "androidx.customview:poolingcontainer", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.datastore", "datastore", "Android DataStore", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.datastore", "datastore-core", "Android DataStore Core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.datastore", "datastore-preferences", "Android Preferences DataStore", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.datastore", "datastore-preferences-core", "Android Preferences DataStore Core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.documentfile", "documentfile", "Android Support Library Document File", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.drawerlayout", "drawerlayout", "Android Support Library Drawer Layout", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.dynamicanimation", "dynamicanimation", "Android Support DynamicAnimation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.emoji2", "emoji2", "Emoji2", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.emoji2", "emoji2-views-helper", "Emoji2 Views Helper", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.exifinterface", "exifinterface", "ExifInterface", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.fragment", "fragment", "fragment", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.fragment", "fragment-ktx", "Fragment Kotlin Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.glance", "glance", "Glance", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.glance", "glance-appwidget", "Glance For App Widgets", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.glance", "glance-appwidget-external-protobuf", "Glance AppWidget External Protobuf", "BSD 3-Clause \"New\" or \"Revised\" License", "https://opensource.org/licenses/BSD-3-Clause"),
    OssLicense("androidx.glance", "glance-appwidget-proto", "Glance AppWidget Protos", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.glance", "glance-material3", "Glance Material", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.graphics", "graphics-path", "Android Graphics Path", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.interpolator", "interpolator", "Android Support Library Interpolators", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.legacy", "legacy-support-core-utils", "Android Support Library core utils", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-common", "Lifecycle-Common", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-common-java8", "Lifecycle-Common for Java 8", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-common-jvm", "Lifecycle-Common", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-livedata", "Lifecycle LiveData", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-livedata-core", "Lifecycle LiveData Core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-livedata-core-ktx", "LiveData Core Kotlin Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-process", "Lifecycle Process", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-runtime", "Lifecycle Runtime", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-runtime-android", "Lifecycle Runtime", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-runtime-compose", "Lifecycle Runtime Compose", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-runtime-compose-android", "Lifecycle Runtime Compose", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-runtime-ktx", "Lifecycle Kotlin Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-runtime-ktx-android", "Lifecycle Kotlin Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-service", "Lifecycle Service", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-viewmodel", "Lifecycle ViewModel", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-viewmodel-android", "Lifecycle ViewModel", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-viewmodel-compose", "Lifecycle ViewModel Compose", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-viewmodel-compose-android", "Lifecycle ViewModel Compose", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-viewmodel-ktx", "Lifecycle ViewModel Kotlin Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-viewmodel-savedstate", "Lifecycle ViewModel with SavedState", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.lifecycle", "lifecycle-viewmodel-savedstate-android", "Lifecycle ViewModel with SavedState", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.loader", "loader", "Android Support Library loader", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.localbroadcastmanager", "localbroadcastmanager", "Android Support Library Local Broadcast Manager", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.navigation", "navigation-common", "Navigation Common", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.navigation", "navigation-common-android", "Navigation Common", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.navigation", "navigation-compose", "Compose Navigation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.navigation", "navigation-compose-android", "Compose Navigation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.navigation", "navigation-runtime", "Navigation Runtime", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.navigation", "navigation-runtime-android", "Navigation Runtime", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.navigationevent", "navigationevent", "Navigation Event", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.navigationevent", "navigationevent-android", "Navigation Event", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.navigationevent", "navigationevent-compose", "NavigationEvent Compose", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.navigationevent", "navigationevent-compose-android", "NavigationEvent Compose", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.print", "print", "Android Support Library Print", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.profileinstaller", "profileinstaller", "Profile Installer", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.resourceinspection", "resourceinspection-annotation", "Android Resource Inspection - Annotations", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.room", "room-common", "Room-Common", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.room", "room-ktx", "Room Kotlin Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.room", "room-runtime", "Room-Runtime", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.savedstate", "savedstate", "Saved State", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.savedstate", "savedstate-android", "Saved State", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.savedstate", "savedstate-compose", "Saved State Compose", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.savedstate", "savedstate-compose-android", "Saved State Compose", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.savedstate", "savedstate-ktx", "SavedState Kotlin Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.sqlite", "sqlite", "SQLite", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.sqlite", "sqlite-android", "SQLite", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.sqlite", "sqlite-framework", "SQLite Framework Integration", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.sqlite", "sqlite-framework-android", "SQLite Framework Integration", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.startup", "startup-runtime", "Startup Runtime", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.tracing", "tracing", "Android Tracing", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.tracing", "tracing-ktx", "Android Tracing Runtime Kotlin Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.transition", "transition", "Transition", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.vectordrawable", "vectordrawable", "Android Support VectorDrawable", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.vectordrawable", "vectordrawable-animated", "Android Support AnimatedVectorDrawable", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.versionedparcelable", "versionedparcelable", "VersionedParcelable", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.viewpager", "viewpager", "Android Support Library View Pager", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.window", "window", "WindowManager", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.window", "window-core", "WindowManager Core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.window", "window-core-android", "WindowManager Core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.work", "work-runtime", "WorkManager Runtime", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("androidx.work", "work-runtime-ktx", "WorkManager Kotlin Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("app.cash.sqldelight", "android-driver", "SQLDelight Android Driver", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("app.cash.sqldelight", "async-extensions", "SQLDelight Async Driver Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("app.cash.sqldelight", "async-extensions-jvm", "SQLDelight Async Driver Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("app.cash.sqldelight", "coroutines-extensions", "SQLDelight Coroutines Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("app.cash.sqldelight", "coroutines-extensions-jvm", "SQLDelight Coroutines Extensions", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("app.cash.sqldelight", "runtime", "SQLDelight Multiplatform Runtime (Experimental)", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("app.cash.sqldelight", "runtime-jvm", "SQLDelight Multiplatform Runtime (Experimental)", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("co.touchlab", "stately-concurrency", "Stately", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("co.touchlab", "stately-concurrency-jvm", "Stately", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("co.touchlab", "stately-concurrent-collections", "Stately", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("co.touchlab", "stately-concurrent-collections-jvm", "Stately", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("co.touchlab", "stately-strict", "Stately", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("co.touchlab", "stately-strict-jvm", "Stately", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("com.abovevacant", "epitaph", "epitaph", "MIT License", "https://opensource.org/license/mit/"),
    OssLicense("com.google.accompanist", "accompanist-drawablepainter", "Accompanist Drawable Painter library", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("com.google.guava", "listenablefuture", "Guava ListenableFuture only", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("com.squareup.okhttp3", "okhttp", "okhttp", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("com.squareup.okhttp3", "okhttp-android", "okhttp", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("com.squareup.okio", "okio", "okio", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("com.squareup.okio", "okio-jvm", "okio", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.coil-kt.coil3", "coil", "coil", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.coil-kt.coil3", "coil-android", "coil", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.coil-kt.coil3", "coil-compose", "coil-compose", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.coil-kt.coil3", "coil-compose-android", "coil-compose", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.coil-kt.coil3", "coil-compose-core", "coil-compose-core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.coil-kt.coil3", "coil-compose-core-android", "coil-compose-core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.coil-kt.coil3", "coil-core", "coil-core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.coil-kt.coil3", "coil-core-android", "coil-core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.coil-kt.coil3", "coil-network-core", "coil-network-core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.coil-kt.coil3", "coil-network-core-android", "coil-network-core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.coil-kt.coil3", "coil-network-ktor3", "coil-network-ktor3", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.coil-kt.coil3", "coil-network-ktor3-android", "coil-network-ktor3", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.insert-koin", "koin-android", "Koin", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.insert-koin", "koin-compose", "Koin", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.insert-koin", "koin-compose-android", "Koin", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.insert-koin", "koin-compose-viewmodel", "Koin", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.insert-koin", "koin-compose-viewmodel-android", "Koin", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.insert-koin", "koin-core", "Koin", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.insert-koin", "koin-core-jvm", "Koin", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.insert-koin", "koin-core-viewmodel", "Koin", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.insert-koin", "koin-core-viewmodel-android", "Koin", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-client-content-negotiation", "ktor-client-content-negotiation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-client-content-negotiation-jvm", "ktor-client-content-negotiation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-client-core", "ktor-client-core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-client-core-jvm", "ktor-client-core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-client-logging", "ktor-client-logging", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-client-logging-jvm", "ktor-client-logging", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-client-okhttp", "ktor-client-okhttp", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-client-okhttp-jvm", "ktor-client-okhttp", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-events", "ktor-events", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-events-jvm", "ktor-events", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-http", "ktor-http", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-http-cio", "ktor-http-cio", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-http-cio-jvm", "ktor-http-cio", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-http-jvm", "ktor-http", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-io", "ktor-io", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-io-jvm", "ktor-io", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-network", "ktor-network", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-network-jvm", "ktor-network", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-serialization", "ktor-serialization", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-serialization-jvm", "ktor-serialization", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-serialization-kotlinx", "ktor-serialization-kotlinx", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-serialization-kotlinx-json", "ktor-serialization-kotlinx-json", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-serialization-kotlinx-json-jvm", "ktor-serialization-kotlinx-json", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-serialization-kotlinx-jvm", "ktor-serialization-kotlinx", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-sse", "ktor-sse", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-sse-jvm", "ktor-sse", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-utils", "ktor-utils", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-utils-jvm", "ktor-utils", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-websocket-serialization", "ktor-websocket-serialization", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-websocket-serialization-jvm", "ktor-websocket-serialization", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-websockets", "ktor-websockets", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.ktor", "ktor-websockets-jvm", "ktor-websockets", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("io.sentry", "sentry", "Sentry SDK", "MIT License", "https://opensource.org/license/mit/"),
    OssLicense("io.sentry", "sentry-android", "Sentry SDK", "MIT License", "https://opensource.org/license/mit/"),
    OssLicense("io.sentry", "sentry-android-core", "Sentry SDK", "MIT License", "https://opensource.org/license/mit/"),
    OssLicense("io.sentry", "sentry-android-ndk", "Sentry SDK", "MIT License", "https://opensource.org/license/mit/"),
    OssLicense("io.sentry", "sentry-android-replay", "Sentry SDK", "MIT License", "https://opensource.org/license/mit/"),
    OssLicense("io.sentry", "sentry-kotlin-multiplatform", "Sentry Kotlin Multiplatform SDK", "MIT License", "https://opensource.org/license/mit/"),
    OssLicense("io.sentry", "sentry-kotlin-multiplatform-android", "Sentry Kotlin Multiplatform SDK", "MIT License", "https://opensource.org/license/mit/"),
    OssLicense("io.sentry", "sentry-native-ndk", "Sentry SDK", "MIT License", "https://opensource.org/license/mit/"),
    OssLicense("org.jetbrains", "annotations", "JetBrains Java Annotations", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.androidx.lifecycle", "lifecycle-common", "Lifecycle-Common", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.androidx.lifecycle", "lifecycle-runtime", "Lifecycle Runtime", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.androidx.lifecycle", "lifecycle-runtime-compose", "Lifecycle Runtime Compose", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.androidx.lifecycle", "lifecycle-viewmodel", "Lifecycle ViewModel", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.androidx.lifecycle", "lifecycle-viewmodel-compose", "Lifecycle ViewModel Compose", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.androidx.lifecycle", "lifecycle-viewmodel-savedstate", "Lifecycle ViewModel with SavedState", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.androidx.navigation", "navigation-common", "Navigation Common", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.androidx.navigation", "navigation-compose", "Compose Navigation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.androidx.navigation", "navigation-runtime", "Navigation Runtime", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.androidx.savedstate", "savedstate", "Saved State", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.androidx.savedstate", "savedstate-compose", "Saved State Compose", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.androidx.window", "window-core", "WindowManager Core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.animation", "animation", "Compose Animation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.animation", "animation-core", "Compose Animation Core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.annotation-internal", "annotation", "Annotation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.collection-internal", "collection", "collections", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.components", "components-resources", "Resources for Compose JB", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.components", "components-resources-android", "Resources for Compose JB", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.foundation", "foundation", "Compose Foundation", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.foundation", "foundation-layout", "Compose Layouts", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.material", "material-ripple", "Compose Material Ripple", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.material3", "material3", "Compose Material3 Components", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.material3", "material3-adaptive-navigation-suite", "Material Adaptive Navigation Suite", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.material3.adaptive", "adaptive", "Material Adaptive", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.runtime", "runtime", "Compose Runtime", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.runtime", "runtime-saveable", "Compose Saveable", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.ui", "ui", "Compose UI", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.ui", "ui-backhandler", "Compose Multiplatform BackHandler", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.ui", "ui-backhandler-android", "Compose Multiplatform BackHandler", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.ui", "ui-geometry", "Compose Geometry", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.ui", "ui-graphics", "Compose Graphics", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.ui", "ui-text", "Compose UI Text", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.ui", "ui-tooling-preview", "Compose UI Preview Tooling", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.ui", "ui-unit", "Compose Unit", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.compose.ui", "ui-util", "Compose Util", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlin", "kotlin-stdlib", "Kotlin Stdlib", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlin", "kotlin-stdlib-jdk7", "Kotlin Stdlib Jdk7", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlin", "kotlin-stdlib-jdk8", "Kotlin Stdlib Jdk8", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlinx", "kotlinx-coroutines-android", "kotlinx-coroutines-android", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlinx", "kotlinx-coroutines-core", "kotlinx-coroutines-core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlinx", "kotlinx-coroutines-core-jvm", "kotlinx-coroutines-core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlinx", "kotlinx-coroutines-slf4j", "kotlinx-coroutines-slf4j", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlinx", "kotlinx-io-bytestring", "kotlinx-io-bytestring", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlinx", "kotlinx-io-bytestring-jvm", "kotlinx-io-bytestring", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlinx", "kotlinx-io-core", "kotlinx-io-core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlinx", "kotlinx-io-core-jvm", "kotlinx-io-core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlinx", "kotlinx-serialization-core", "kotlinx-serialization-core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlinx", "kotlinx-serialization-core-jvm", "kotlinx-serialization-core", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlinx", "kotlinx-serialization-json", "kotlinx-serialization-json", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlinx", "kotlinx-serialization-json-io", "kotlinx-serialization-json-io", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlinx", "kotlinx-serialization-json-io-jvm", "kotlinx-serialization-json-io", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jetbrains.kotlinx", "kotlinx-serialization-json-jvm", "kotlinx-serialization-json", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.jspecify", "jspecify", "JSpecify annotations", "Apache License 2.0", "https://www.apache.org/licenses/LICENSE-2.0"),
    OssLicense("org.slf4j", "slf4j-api", "SLF4J API Module", "MIT", "https://opensource.org/license/mit"),
    // Not a Maven dependency: the app-wide type family bundled as a Compose
    // font resource in :core:designsystem (see core/designsystem/FONTS.md).
    OssLicense("com.schibsted", "schibsted-grotesk", "Schibsted Grotesk (font)", "SIL Open Font License 1.1", "https://openfontlicense.org"),
)
