#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Apple setup for Muviss (EPIC 35 #78, EPIC 36 #79, ADR 0016, ADR 0019).
#
#   scripts/release/apple-setup.sh        (from the repo root)
#
# Owner-only, run once after joining the Apple Developer Program. Produces:
#   local.properties   APPLE_TEAM_ID (not secret; for local builds)
#   GitHub variable    APPLE_TEAM_ID
#   GitHub secrets     APP_STORE_CONNECT_KEY_ID, APP_STORE_CONNECT_ISSUER_ID,
#                      APP_STORE_CONNECT_KEY_P8      (fastlane TestFlight/App
#                                                      Store, and notarytool)
#                      MACOS_DEVELOPER_ID_P12_BASE64,
#                      MACOS_DEVELOPER_ID_P12_PASSWORD (signs the DMG)
# No workflow reads these yet: EPIC 35/36 add the jobs, under these names.
# ──────────────────────────────────────────────────────────────────────────

cd "$(dirname "$0")/../.." || exit 1
ENV_FILE="local.properties"   # gitignored; already holds TMDB_*/SENTRY_* the same way
APP_ID="com.codingpit.muviss"
WIDGET_ID="com.codingpit.muviss.MuvissWidget"
APP_GROUP="group.com.codingpit.muviss"

TOTAL_STAGES=7

banner "Apple setup for Muviss"

stage "Join the Apple Developer Program"
say "Everything else needs a paid membership (99 USD/year)."
open_url "https://developer.apple.com/programs/enroll/"
step "Enrol as an individual or as an organisation (an organisation needs a D-U-N-S number)."
step "Apple reviews it, usually within 48 hours. You get an email when it is active."
note "Already a member? Just continue."
pause "Press Enter once the membership is active"

stage "Team ID"
open_url "https://developer.apple.com/account"
step "Scroll to Membership details and copy the Team ID (10 characters)."
ask APPLE_TEAM_ID "Paste the Team ID:"
write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"
set_var APPLE_TEAM_ID "$APPLE_TEAM_ID"
note "For local Xcode builds, also put it in app/iosApp/Configuration/Config.xcconfig"
note "as TEAM_ID=$APPLE_TEAM_ID — but do not commit that line (docs/RELEASING.md §11)."
pause

stage "App Group"
say "The widget reads the app's database through $APP_GROUP (ADR 0016)."
open_url "https://developer.apple.com/account/resources/identifiers/list/applicationGroup"
step "Click +, choose App Groups, Continue."
step "Description: Muviss. Identifier: $APP_GROUP. Register."
pause "Press Enter once the App Group exists"

stage "App IDs for the app and the widget"
open_url "https://developer.apple.com/account/resources/identifiers/add/bundleId"
step "App IDs → App → Continue. Description: Muviss. Bundle ID (Explicit): $APP_ID."
step "Capabilities: tick App Groups and Sign In with Apple (ADR 0019 needs it for sync)."
step "Register, then open it again → App Groups → Configure → tick $APP_GROUP → Save."
step "Repeat for the widget: Bundle ID $WIDGET_ID, capability App Groups only, same group."
note "If Xcode already created either id under automatic signing, edit it instead of adding."
pause "Press Enter once both App IDs have the App Group"

stage "The app in App Store Connect"
open_url "https://appstoreconnect.apple.com/apps"
step "Click + → New App. Platform iOS. Name: Muviss (if it's taken, note what you used)."
step "Primary language: English (U.S.). Bundle ID: $APP_ID. SKU: muviss. Full access."
note "The listing itself comes from fastlane metadata later (EPIC 33/35), not from here."
pause "Press Enter once the app record exists"

stage "App Store Connect API key"
say "One key lets CI upload to TestFlight and notarise the macOS DMG, with no Apple ID password."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "Team Keys → + (Generate API Key). Name: Muviss CI. Access: App Manager. Generate."
step "Copy the Issuer ID shown above the table, and the new key's Key ID."
warn "Download the .p8 now: Apple only lets you download it once."
ask APP_STORE_CONNECT_ISSUER_ID "Paste the Issuer ID:"
ask APP_STORE_CONNECT_KEY_ID "Paste the Key ID:"
ask P8_PATH "Path to the downloaded AuthKey_<KeyID>.p8:"
P8_PATH="${P8_PATH/#\~/$HOME}"
if [[ -f "$P8_PATH" ]]; then
  set_secret APP_STORE_CONNECT_ISSUER_ID "$APP_STORE_CONNECT_ISSUER_ID"
  set_secret APP_STORE_CONNECT_KEY_ID "$APP_STORE_CONNECT_KEY_ID"
  set_secret APP_STORE_CONNECT_KEY_P8 "$(cat "$P8_PATH")"
  note "Keep the .p8 somewhere safe (a password manager), then delete the loose copy."
else
  SKIPPED+=("App Store Connect API key: $P8_PATH not found — re-run this stage")
  warn "No file at $P8_PATH; nothing was stored."
fi
pause

stage "Developer ID certificate for the macOS DMG"
say "Signing plus notarisation is what stops Gatekeeper refusing the DMG (EPIC 36)."
step "On this Mac: Keychain Access → Certificate Assistant → Request a Certificate"
step "From a Certificate Authority. Your email, 'Saved to disk'. Save the .certSigningRequest."
open_url "https://developer.apple.com/account/resources/certificates/add"
step "Choose Developer ID Application (G2 Sub-CA), upload the request, download the .cer."
step "Double-click the .cer to add it to your login keychain."
step "Keychain Access → My Certificates → right-click 'Developer ID Application: …' →"
step "Export as .p12, with a password you choose."
ask P12_PATH "Path to the exported .p12:"
P12_PATH="${P12_PATH/#\~/$HOME}"
ask_secret MACOS_DEVELOPER_ID_P12_PASSWORD "The .p12's password:"
if [[ -f "$P12_PATH" ]]; then
  set_secret MACOS_DEVELOPER_ID_P12_BASE64 "$(base64 -i "$P12_PATH" | tr -d '\n')"
  set_secret MACOS_DEVELOPER_ID_P12_PASSWORD "$MACOS_DEVELOPER_ID_P12_PASSWORD"
  note "Delete the loose .p12 once it is stored; the keychain keeps the original."
else
  SKIPPED+=("Developer ID certificate: $P12_PATH not found — re-run this stage")
  warn "No file at $P12_PATH; nothing was stored."
fi
pause

finish
say "Next: tell the agent the Team ID is in, so it can wire EPIC 35/36 (#78, #79)"
say "and build the widget (#23). Sign in with Apple for sync is configured later,"
say "in Supabase, as part of EPIC 32 (#75)."
