// Generates :app:androidApp's baseline profile (EPIC 34 / #77). Not part of any
// CI lane: it needs a device, so the profile is generated by hand and the
// result committed under app/androidApp/src/release/generated/baselineProfiles/.
//
//   ./gradlew :app:androidApp:generateReleaseBaselineProfile   # emulator or phone attached
//
// Regenerate when the startup path or the main screens change materially.
plugins {
    alias(libs.plugins.androidTest)
    alias(libs.plugins.baselineprofile)
}

android {
    namespace = "com.codingpit.muviss.baselineprofile"
    compileSdk =
        libs.versions.android.compileSdk
            .get()
            .toInt()

    defaultConfig {
        // Profile generation needs API 28+ (rooted) or 33+ (any device).
        minSdk = 28
        targetSdk =
            libs.versions.android.targetSdk
                .get()
                .toInt()
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    targetProjectPath = ":app:androidApp"

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

baselineProfile {
    // A connected emulator or phone, not a Gradle-managed device: a GMD
    // downloads a system image on every fresh machine, for a task run by hand.
    useConnectedDevices = true
}

dependencies {
    implementation(libs.androidx.testExt.junit)
    implementation(libs.androidx.uiautomator)
    implementation(libs.androidx.benchmark.macroJunit4)
}
